import { TYPE_DONE, TYPE_ERROR } from '../type';

export const USER_TYPES = {
	SET_LOGINED: 'user/SET_LOGINED',
	LOGOUT: 'user/LOGOUT',

	GET_USER: 'user/GET_USER',
	GET_USER_DONE: TYPE_DONE('user/GET_USER'),
	GET_USER_ERROR: TYPE_ERROR('user/GET_USER'),
	GET_USERS: 'user/GET_USERS',
	GET_USERS_DONE: TYPE_DONE('user/GET_USERS'),
	GET_USERS_ERROR: TYPE_ERROR('user/GET_USERS'),
	UPDATE_USER: 'user/UPDATE_USER',
	UPDATE_USER_DONE: TYPE_DONE('user/UPDATE_USER'),
	UPDATE_USER_ERROR: TYPE_ERROR('user/UPDATE_USER'),
	DELETE_USER: 'user/DELETE_USER',
	DELETE_USER_DONE: TYPE_DONE('user/DELETE_USER'),
	DELETE_USER_ERROR: TYPE_ERROR('user/DELETE_USER'),
};
