import { TYPE_DONE, TYPE_ERROR } from '../type';

export const WORK_TYPES = {
	RESET: 'work/RESET',

	GET_WORK: 'work/GET_WORK',
	GET_WORK_DONE: TYPE_DONE('work/GET_WORK'),
	GET_WORK_ERROR: TYPE_ERROR('work/GET_WORK'),

	GET_WORKS: 'work/GET_WORKS',
	GET_WORKS_DONE: TYPE_DONE('work/GET_WORKS'),
	GET_WORKS_ERROR: TYPE_ERROR('work/GET_WORKS'),

	CREATE_WORKS: 'work/CREATE_WORKS',
	CREATE_WORKS_DONE: TYPE_DONE('work/CREATE_WORKS'),
	CREATE_WORKS_ERROR: TYPE_ERROR('work/CREATE_WORKS'),

	UPDATE_WORKS: 'work/UPDATE_WORKS',
	UPDATE_WORKS_DONE: TYPE_DONE('work/UPDATE_WORKS'),
	UPDATE_WORKS_ERROR: TYPE_ERROR('work/UPDATE_WORKS'),

	DELETE_WORKS: 'work/DELETE_WORKS',
	DELETE_WORKS_DONE: TYPE_DONE('work/DELETE_WORKS'),
	DELETE_WORKS_ERROR: TYPE_ERROR('work/DELETE_WORKS'),
};
