import { TYPE_DONE, TYPE_ERROR } from '../type';

export const TIMES_TYPES = {
	GET_CATEGORIES: 'times/GET_CATEGORIES',
	GET_CATEGORIES_DONE: TYPE_DONE('times/GET_CATEGORIES'),
	GET_CATEGORIES_ERROR: TYPE_ERROR('times/GET_CATEGORIES'),
	CREATE_CATEGORY: 'times/CREATE_CATEGORY',
	CREATE_CATEGORY_DONE: TYPE_DONE('times/CREATE_CATEGORY'),
	CREATE_CATEGORY_ERROR: TYPE_ERROR('times/CREATE_CATEGORY'),
	UPDATE_CATEGORY: 'times/UPDATE_CATEGORY',
	UPDATE_CATEGORY_DONE: TYPE_DONE('times/UPDATE_CATEGORY'),
	UPDATE_CATEGORY_ERROR: TYPE_ERROR('times/UPDATE_CATEGORY'),
	DELETE_CATEGORY: 'times/DELETE_CATEGORY',
	DELETE_CATEGORY_DONE: TYPE_DONE('times/DELETE_CATEGORY'),
	DELETE_CATEGORY_ERROR: TYPE_ERROR('times/DELETE_CATEGORY'),

	SET_TAGS: 'times/SET_TAGS',
	CREATE_TAG: 'times/CREATE_TAG',
	CREATE_TAG_DONE: TYPE_DONE('times/CREATE_TAG'),
	CREATE_TAG_ERROR: TYPE_ERROR('times/CREATE_TAG'),
	UPDATE_TAG: 'times/UPDATE_TAG',
	UPDATE_TAG_DONE: TYPE_DONE('times/UPDATE_TAG'),
	UPDATE_TAG_ERROR: TYPE_ERROR('times/UPDATE_TAG'),
	DELETE_TAG: 'times/DELETE_TAG',
	DELETE_TAG_DONE: TYPE_DONE('times/DELETE_TAG'),
	DELETE_TAG_ERROR: TYPE_ERROR('times/DELETE_TAG'),
};
